### ISSUE TITLE
[N64] MLB Ken Griffey Jr.: Flickering logos' images

### ISSUE THREAD

**Issue by Shideravan** [ares-emulator/ares#132]
The issue happens in Mupen 64 plus and Glide N64 but there they're related to their graphics plugin (https://github.com/gonetz/GLideN64/issues/1664)
This issue does not happen in real console (https://www.youtube.com/watch?v=koDN9_WNsSo)

ares e6948d2

**Comment by meauxdal** [comment]
Video reference below of current ares behavior as of 20251209. There are two noticeable issues. There are line glitches during scene changes, as well as flickering pixels (these are most noticeable on the 2nd and 3rd cycles of the title screen).

**Video reference:**
https://www.youtube.com/watch?v=sALVH6a7TIw

**Rom Information:**
```
game
  name:     Major League Baseball Featuring Ken Griffey Jr. (USA)
  title:    Major League Baseball Featuring Ken Griffey Jr. (USA)
  sha256:   c489d247f13d0ac6ba71b3bbc6052100a8d582576df8e2a80988ee20b1dcb821
  region:   NTSC
  id:       NKGE
  revision: 1.0
  controllers
    port1
      cpak
    port2
      rpak
    port3
    port4
  board
    cic: CIC-NUS-6103
    memory
      type: ROM
      size: 0x1000000
      content: Program
    memory
      type: RAM
      size: 0x8000
      content: Save
```
Tested on ares nightly 20251209 - **ares v146-190-gec37caccf**

**Comment by loganmc10** [comment]
This is probably related to/fixed by https://github.com/ares-emulator/ares/pull/2562

**Comment by meauxdal** [comment]
Both issues still present on ares v148. Line glitches during scene changes are still there, as well as the flickering on subsequent appearances of the title screen (first appearance is normal).

**Comment by meauxdal** [comment]
As of the latest nightly (https://github.com/ares-emulator/ares/commit/31526ded9196b046b0b5ce1769f14335eba9cc33), **the scene transition issue is fixed**! 

However, the title screen corruption still occurs: https://youtu.be/sG8SQkCoUvs

Note: the first appearance of the title screen is always correct, but each time it reoccurs, it will have random flickering lines.
